### ISSUE TITLE
Multiple messages, some got lost.

### ISSUE THREAD

**Issue by bruno-m-antunes-alb** [vivianaranha/TvOS_Remote#1]
When sending multiple messages (every time a touchMoved is fired for example) some of the messages are received as "null" on the Apple TV.

Any ideias? 

Thanks

**Comment by vivianaranha** [comment]
will look it up - Myabe will add a return type

On Wed, Sep 23, 2015 at 6:20 AM, ShUr1k3n notifications@github.com wrote:

> When sending multiple messages (every time a touchMoved is fired for
> example) some of the messages are received as "null" on the Apple TV.
> 
> Any ideias?
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vivianaranha/TvOS_Remote/issues/1.

## 

Vivian Aranha

**Comment by streamside7** [comment]
Can this library also do bi directional communication? Is this Bluetooth or WiFi/IP based? It works wonderfully. Very nice! Thank you!

**Comment by vivianaranha** [comment]
It works on Bluetooth. If you want I can make it such that it support bodirectional. Currently I am seeing some bugs. So working on those. Will update as soon as I get opportunity. 

Also trying to add both wifi/Bluetooth functionality

**Comment by streamside7** [comment]
Bidirectional support would be awesome! And support for multiple devices at the same time would be even better still! Like I said, awesome job. It works so seamlessly. Very impressive!

**Comment by vassilisimon** [comment]
Would be awesome if this would be WiFi-based, because with BLE it's not possible to connect more than 2 iDevices. Yeah, and bidirectional would be great too.

**Comment by MaartenW** [comment]
How do you know when the devices are linked?

**Comment by samtout** [comment]
I'm getting the following error on "TheApp" version. Any idea?
"ignoring file <path>/AppleTVApp/TheApp/TheApp/libRemoteReceiver.a, missing required architecture x86_64 in file <path>/AppleTVApp/TheApp/TheApp/libRemoteReceiver.a (3 slices)"
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_RemoteReceiver", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by streamside7** [comment]
@samtout: My guess is you're seeing this on the simulator? Could this be a matter of not being able to run in the simulator? If so, the problem should disappear on the actual Apple TV. Just a guess.

**Comment by samtout** [comment]
Thanks @streamside7 
That's a good thought. But running it on the actual TV still gave me: "building for tvOS, but linking in object file built for iOS, for architecture arm64"
Any thoughts?

**Comment by Zodor** [comment]
I'm getting a: TestController[1588:696670] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array' 
when executing sendInfo.

Any ideas why
The Receiver is not up and running, but should I get this error?

**Comment by greggmojica** [comment]
I need help with this too. I have the error Undefined symbols for architecture x86_64:

Any ideas?

**Comment by vivianaranha** [comment]
I have provided the entire Project in Projects folder - Just use .h and .m files instead of Library.

Also I never tested on Sim - it sucks on sim as its pretty useless. I created a bunch of apps using this - You can check an example at https://itunes.apple.com/us/app/twins-merge-em!!/id1044143620?mt=8

**Comment by jonnyijapan** [comment]
Zodor: I just got the same/similar error, and the reason for that was WIFI was turned off on my iPhone. Your error might have the same origin, or there could be something else that makes your iPhone and AppleTV unable to connect. That's why it crashes - because the sender class unfortunately crashes when no connection exist and you try to send a message. My closed issue is: https://github.com/vivianaranha/TvOS_Remote/issues/4
